#!/usr/bin/env python3
# PREREQ: Requires gradescope lib be on $PYTHONPATH

import os
from pathlib import Path
import sys

# Harness points gradescope lib to $PWD/autograder
testdir = Path(os.getcwd()) / 'autograder'

os.environ['PATH_CODE']     = str(testdir / 'submission')
os.environ['PATH_RESULTS']  = os.devnull
os.environ['PATH_METADATA'] = str(testdir / 'example_metadata.json')

# Functional section
from gradescope import PrereqError, Tester

tester = Tester()

@tester.prerequisite()
def dummy_prereq():
  _ = PrereqError("Nope", std_out="Still Nothing")

tester.no_tests()

if __name__ == '__main__':
  res = tester.exec()
  if tester.failed:
    sys.exit(1)
  res.save()
  print("Okay")
